Quiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authentified/', include('authentified.urls')),
    url(r'^exam/', include('exam.urls')),

]

exam/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index , name='index'),
    url(r'^(?P<exam_id>[0-9]+)/$', views.detail,name='detail'),
    url(r'^(?P<exam_id>[0-9]+)/reponse/$', views.reponse, name='reponse'),
    url(r'^(?P<exam_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<Quest_id>[0-9]+)/editfree/$', views.editfree, name='editfree'),
    url(r'^(?P<Quest_id>[0-9]+)/editmulti/$', views.editmulti, name='editmulti'),
    url(r'^(?P<Quest_id>[0-9]+)/editone/$', views.editone, name='editone'),
    url(r'^create/$', views.create_view, name='create_view'),
    url(r'^createQuest/$', views.createExam, name='createExam'),
    url(r'^secondeQuest/$', views.secondeQuest, name='secondeQuest'),
    url(r'^(?P<exam_id>[0-9]+)/addQuest/$', views.addQuest, name='addQuest'),
    url(r'^(?P<exam_id>[0-9]+)/deleteEXam/$', views.deleteEXam, name='deleteEXam'),
    url(r'^(?P<question_id>[0-9]+)/deleteQuest/$', views.deleteQuest, name='deleteQuest'),
    url(r'^(?P<exam_id>[0-9]+)/passe/$', views.passe, name='passe'),
    url(r'^(?P<exam_id>[0-9]+)/passe/(?P<Quest_id>[0-9]+)$', views.passeQuest, name='passeQuest'),
    url(r'^(?P<exam_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'^(?P<exam_id>[0-9]+)/invitating/$', views.invitating, name='invitating'),
    url(r'^addUser/$', views.addUser, name='addUser'),
    url(r'^consultUsers/$', views.consultUsers, name='consultUsers'),
    url(r'^sendMail/$', views.sendMail, name='sendMail'),
    url(r'^(?P<exam_id>[0-9]+)/passeExam/$', views.passeStudent, name='passeStudent'),
    url(r'^(?P<exam_id>[0-9]+)/passeExam/(?P<Quest_id>[0-9]+)$', views.passeQuestStudent, name='passeQuestStudent'),
    url(r'^(?P<exam_id>[0-9]+)/resultExam/$', views.resultStudent, name='resultStudent'),
    url(r'^becameProf/$', views.becameProf, name='becameProf'),
    url(r'^MyExams/$', views.MyExams , name='MyExams'),
    url(r'^correction/$', views.correction , name='correction'),
    url(r'^correction/(?P<exam_id>[0-9]+)/$', views.correctionExam , name='correctionExam'),
    url(r'^certified/$', views.certified , name='certified'),
    url(r'^certified/(?P<exam_id>[0-9]+)/$', views.imprimeCertif , name='imprimeCertif'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^updateProfile/$', views.updateProfile, name='updateProfile'),

              ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

exam/models.py
from django.db import models
from django.contrib.auth.models import User
from authentified.models import Profile
import datetime
# Create your models here.

class Exam(models.Model):
    name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='exam_image',blank=True,null=True)
    description = models.CharField(max_length=50,default='')
    category = models.CharField(max_length=50,default='')
    score = models.IntegerField(default=0)
    timer = models.IntegerField(default=0)
    type=models.CharField(max_length=50,default='')
    certified=models.BooleanField(default=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=1)



    def __str__(self):
         return self.name

class Question(models.Model):
    examen = models.ForeignKey(Exam,on_delete=models.CASCADE)
    description = models.CharField(max_length=1000,default='')
    points = models.IntegerField(default=0)
    header_text = models.CharField(max_length=1000,default='')
    footer_text = models.CharField(max_length=1000,default='')
    success_msg = models.CharField(max_length=1000,default='')
    fail_msg = models.CharField(max_length=1000,default='')


    def __str__(self):
         return self.description

class one_answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    answer_variant = models.CharField(max_length=50)
    answer_description = models.CharField(max_length=1000)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_variant
class Multi_choice_answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    multi_variant = models.CharField(max_length=50)
    multi_description = models.CharField(max_length=1000)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.multi_variant

class Free_text(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)


    def __str__(self):
        return self.text

class Reponse(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    exam=models.ForeignKey(Exam,on_delete=models.CASCADE, related_name='Exam',default=1 )
    One_answer=models.ForeignKey(one_answer,on_delete=models.CASCADE, related_name='One_answer')
    multi_choice_answer=models.ForeignKey(Multi_choice_answer,on_delete=models.CASCADE, related_name='multi_choice_answer')
    free_text=models.CharField(max_length=1000,default='')#enregistrer le score ou l id!!!!!!!!!
    score_question=models.IntegerField(default=0)
    nbr_attempt=models.IntegerField(default=1)

class studentClass(models.Model):
    professor=models.ForeignKey(User,on_delete=models.CASCADE,related_name='prof',default=1)
    student=models.ForeignKey(User,on_delete=models.CASCADE,related_name='student',blank=True,null=True)
    exam=models.ForeignKey(Exam,on_delete=models.CASCADE,related_name='exam',blank=True,null=True)
    email_invited=models.CharField(max_length=1000,default="")

class invitation(models.Model):
    prof = models.ForeignKey(User, on_delete=models.CASCADE,related_name='professor',  default=1)
    student = models.ForeignKey(User, on_delete=models.CASCADE,  default=0)
    exams = models.ForeignKey(Exam, on_delete=models.CASCADE,    default=0)
    non_passed=models.BooleanField(default=True)
    attempt=models.IntegerField(default=0)

class certificat(models.Model):
    exam=models.ForeignKey(Exam,on_delete=models.CASCADE,blank=True,null=True)
    student=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    score=models.IntegerField(default=0)
    date = models.DateField(default=datetime.date.today)
#date a verifier

exam/views.py
from django.shortcuts import render,redirect
from .models import Question,Exam,one_answer,Free_text,Multi_choice_answer,Reponse,studentClass,invitation,certificat
# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import loader
from random import *
from authentified.models import Profile
from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
import pusher
def index(request):



    if request.user.is_authenticated():


        profile=Profile.objects.get(user=request.user)
        if profile.is_prof==True:
            all_exam = Exam.objects.filter(user=request.user)
            if id in request.session:
                del request.session['id']
            my_template='exam/baseProf.html'
            context = {
                'my_template': my_template,
                'all_exam': all_exam,
            }
            return render(request, 'exam/index.html',context)
        else:
            my_template='exam/base.html'
            invite =invitation.objects.filter(student=request.user)
            context={
                'my_template': my_template,
                'invite':invite,
            }
            return render(request, 'exam/studentIndex.html',context)




    else:
        return render(request, "firstPage/index.html")



def edit(request,exam_id):
    exam = Exam.objects.get(pk=exam_id)
    if request.method=="POST":
        examName = request.POST['examName']
        ExamDesc = request.POST['ExamDesc']
        category = request.POST['category']

        exam.name = examName
        exam.description = ExamDesc
        exam.category = category
        exam.save()
        return redirect('/exam/')
    template = loader.get_template('exam/edit.html')
    my_template = 'exam/baseProf.html'

    context = {
        'examen_id': exam_id,
      'examen': exam,
        'my_template': my_template,

    }

    return HttpResponse(template.render(context, request))



def detail(request,exam_id):


    exam = Exam.objects.get(pk=exam_id)
    template = loader.get_template('exam/les_questions.html')
    my_template = 'exam/baseProf.html'

    context = {
        'my_template': my_template,

        'examen_id': exam_id,
      'examen': exam,

    }

    return HttpResponse(template.render(context, request))

def editone(request,Quest_id):
    question = Question.objects.get(pk=Quest_id)
    if request.user.is_authenticated():
        if request.method == 'POST':
            Description = request.POST['Description']
            Header_text = request.POST['Header_text']
            Footer_text = request.POST['Footer_text']
            Success_msg = request.POST['Success_msg']
            Fail_msg = request.POST['Fail_msg']
            points = request.POST['points']
            question.description=Description
            question.header_text = Header_text
            question.footer_text = Footer_text
            question.success_msg = Success_msg
            question.fail_msg = Fail_msg
            question.points = points
            question.save()
            ID1=request.POST['id1']
            ID2 = request.POST['id2']
            ID3 = request.POST['id3']
            ans1=one_answer.objects.get(pk=ID1)
            ans2=one_answer.objects.get(pk=ID2)
            ans3=one_answer.objects.get(pk=ID3)

            answer_variant = request.POST['answer_variant1']
            answer_description = request.POST['answer_description1']
            pointsAns = request.POST['points1']
            answer_variant2 = request.POST['answer_variant2']
            answer_description2 = request.POST['answer_description2']
            pointsAns2 = request.POST['points2']
            answer_variant3 = request.POST['answer_variant3']
            answer_descriptio3 = request.POST['answer_description3']
            pointsAn3 = request.POST['points3']

            ans1.answer_variant = answer_variant
            ans1.answer_description = answer_description
            ans1.points = pointsAns
            ans1.save()
            ans2.answer_variant = answer_variant2
            ans2.answer_description = answer_description2
            ans2.points = pointsAns2
            ans2.save()
            ans3.answer_variant = answer_variant3
            ans3.answer_description = answer_descriptio3
            ans3.points = pointsAn3
            ans3.save()



            return redirect("/exam/")
        else:
            template = loader.get_template('exam/editOneAnser.html')
            context = {
                'question': question,

            }

            return HttpResponse(template.render(context, request))

def editmulti(request,Quest_id):
    question = Question.objects.get(pk=Quest_id)
    if request.user.is_authenticated():
        if request.method == 'POST':
            Description = request.POST['Description']
            Header_text = request.POST['Header_text']
            Footer_text = request.POST['Footer_text']
            Success_msg = request.POST['Success_msg']
            Fail_msg = request.POST['Fail_msg']
            points = request.POST['points']
            question.description=Description
            question.header_text = Header_text
            question.footer_text = Footer_text
            question.success_msg = Success_msg
            question.fail_msg = Fail_msg
            question.points = points
            question.save()
            ID1=request.POST['id1']
            ID2 = request.POST['id2']
            ID3 = request.POST['id3']
            ans1=Multi_choice_answer.objects.get(pk=ID1)
            ans2=Multi_choice_answer.objects.get(pk=ID2)
            ans3=Multi_choice_answer.objects.get(pk=ID3)

            answer_variant = request.POST['answer_variant1']
            answer_description = request.POST['answer_description1']
            pointsAns = request.POST['points1']
            answer_variant2 = request.POST['answer_variant2']
            answer_description2 = request.POST['answer_description2']
            pointsAns2 = request.POST['points2']
            answer_variant3 = request.POST['answer_variant3']
            answer_descriptio3 = request.POST['answer_description3']
            pointsAn3 = request.POST['points3']

            ans1.multi_variant = answer_variant
            ans1.multi_description = answer_description
            ans1.points = pointsAns
            ans1.save()
            ans2.multi_variant = answer_variant2
            ans2.multi_description = answer_description2
            ans2.points = pointsAns2
            ans2.save()
            ans3.multi_variant = answer_variant3
            ans3.multi_description = answer_descriptio3
            ans3.points = pointsAn3
            ans3.save()



            return redirect("/exam/")
        else:
            template = loader.get_template('exam/EditMulti.html')
            context = {
                'question': question,

            }

            return HttpResponse(template.render(context, request))

def editfree(request,Quest_id):
    question = Question.objects.get(pk=Quest_id)
    if request.user.is_authenticated():
        if request.method == 'POST':
            Description = request.POST['Description']
            Header_text = request.POST['Header_text']
            Footer_text = request.POST['Footer_text']
            Success_msg = request.POST['Success_msg']
            Fail_msg = request.POST['Fail_msg']
            points = request.POST['points']
            question.description=Description
            question.header_text = Header_text
            question.footer_text = Footer_text
            question.success_msg = Success_msg
            question.fail_msg = Fail_msg
            question.points = points
            question.save()
            id = request.POST['id']
            freeText=Free_text.objects.get(pk=id)
            text =request.POST['text']
            freeText.text=text
            freeText.save()
            return redirect("/exam/")
        else:
            template = loader.get_template('exam/EditFreeText.html')
            context = {
                'question': question,

            }

            return HttpResponse(template.render(context, request))

def reponse(request,exam_id):
    exam = Exam.objects.get(pk=exam_id)
    template = loader.get_template('exam/valider.html')


    try:
        choice = one_answer.objects.get(pk=request.POST['choice'])


    except(KeyError):

        exam.total = 0
        exam.save()
        context = {
            'exam': exam,
            'exam_id': exam_id,
            'message':'choix non valide',

        }
        return HttpResponse(template.render(context, request))
    else:
        exam.total = choice.note
        exam.save()
        context = {
            'exam': exam,
            'exam_id': exam_id,

        }
        return HttpResponse(template.render(context, request))

def create_view(request):

     if request.user.is_authenticated():
         return render(request, 'exam/createExam.html')

def createExam(request):
     if request.user.is_authenticated():
        if request.method == 'POST' and request.POST['examName']:
            exam = Exam()
            examName = request.POST['examName']
            ExamDesc = request.POST['ExamDesc']
            category = request.POST['category']
            type = request.POST['type']
            timer = request.POST['timer']
            score = request.POST['score']

            if "certified" in request.POST:
                certified=request.POST['certified']
                if certified =='yes':
                    exam.certified=True
                else:
                    exam.certified=False
            if 'logo' in request.FILES:
                logo = request.FILES['logo']
                exam.logo = logo
            print(timer)
            exam.name = examName
            exam.description = ExamDesc

exam/templates/exam/PasseExamStudent.html
{% extends 'exam/baseProf.html' %}


{% block title %}Quiz{% endblock %}

{% block content %}

                            <div class="card" >
                                <div class="card-header">
                                    <h4>Exam {{examen.name}}</h4>
                                </div>
                                <div class="card-body">

<div class="col-lg-8" >
    <center><h1>Commancer</h1></center>
</div>
<div class="col-lg-4" >
                                                 {% for question in examen.question_set.all %}
    {%if forloop.counter == 1 %}
<a href="{{firstid}}" class="btn btn-block btn-success">commancer</a>
{%endif%}
                                            {%endfor%}

</div>

                                </div>
                            </div>





{% endblock %}

exam/templates/exam/QuestExamStudent.html
{% extends 'exam/baseProf.html' %}

{% block title %}Quiz{% endblock %}

{% block content %}

<div class="col-lg-8" >


                            <div class="card">
                                <div class="card-header">
                                    <h4>Exam {{examen.name}}</h4>
                                </div>
                                <div class="card-body">
                            {% for question in liste %}
                                                                                {%if forloop.counter0 == i %}

                                    <form method="post" action="{{question.id}}">
                                        {% elif forloop.counter == length%}
                                                                            <form method="post" action="">

 {%endif%}

                                                                                    {%endfor%}

                                     {%csrf_token%}
<input type="hidden" value="{{quest.id}}" name="id">

     {%if quest.multi_choice_answer_set.all %}
                                                 <div class="col col-md-3"><label class=" form-control-label">{{quest.description}}</label></div>
                            <div class="col col-md-9">
                              <div class="form-check">
                                   {%for choix in quest.multi_choice_answer_set.all %}
                                <div class="radio">
                                  <label for="{{choix.id}}" class="form-check-label ">
                            {%if exist %}
                               {%for reponse in listeSession%}
                                  {%if reponse.0 == quest.id %}


                                    {%if  choix.id in reponse.1%}


                                    <input type="checkbox"  name="radiosM" value="{{choix.id}}" class="form-check-input" checked>{{choix.multi_variant}}
                                      {% else %}
                                      <input type="checkbox"  name="radiosM" value="{{choix.id}}" class="form-check-input">{{choix.multi_variant}}
                                      {% endif %}


                                  {%endif%}
                                {%endfor%}
<!--problem fel selecter-->
                             {% else %}
                                      <input type="checkbox"  name="radiosM" value="{{choix.id}}" class="form-check-input">{{choix.multi_variant}}
                             {%endif%}
                                  </label>
                                </div>

                                  {%endfor%}

                              </div>
                            </div>

               {%endif%}
{%if quest.one_answer_set.all %}
                                                 <div class="col col-md-3"><label class=" form-control-label">{{quest.description}}</label></div>
                            <div class="col col-md-9">
                              <div class="form-check">
                                   {%for choix in quest.one_answer_set.all %}
                                <div class="radio">
                                  <label for="{{choix.id}}" class="form-check-label ">
                                      {%if exist %}
                                      {%for reponse in listeSession%}
                                      {%if reponse.0 == quest.id %}
                                      {%if reponse.1 == choix.id %}
                                    <input type="radio"  name="radios"value="{{choix.id}}" class="form-check-input" checked="checked">{{choix.answer_variant}}
                                      {% else %}
                                    <input type="radio"  name="radios"value="{{choix.id}}" class="form-check-input">{{choix.answer_variant}}
                                  {%endif%}
                                      {%endif%}
                                      {%endfor%}

                                      {% else %}
                                    <input type="radio" id="{{choix.id}}" name="radios"value="{{choix.id}}" class="form-check-input">{{choix.answer_variant}}
                                  {%endif%} </label>
                                </div>

                                  {%endfor%}
                                  <a href="#{{question.id}}" class="btn btn-block ">{{forloop.counter}}</a>

                              </div>
                            </div>

               {%endif%}
                                {%if quest.free_text_set.all %}



          {%for choix in quest.free_text_set.all %}
 <div class="row form-group">
                            <div class="col col-md-3"><label for="textarea-input" class=" form-control-label">{{quest.description}}</label></div>
<div class="col-12 col-md-9">

                                      {%if exist %}
                                      {%for reponse in listeSession%}

    {%if reponse.0 == quest.id %}
    <textarea name="text"  rows="9"  placeholder="Content..." class="form-control">{{reponse.1}}</textarea>
{%endif%}
                            {%endfor%}
    {% else %}        <textarea name="text" id="textarea-input" rows="9"  placeholder="Content..." class="form-control"></textarea>
{%endif%}


    </div>
                          </div>

    <br>{%endfor%}


                                               {%endif%}
<center><input type="submit" value="submit" class="btn btn-danger" name="submit">
</center>
                                                                                <input id="time" type="text" value="{{time}}" name="time">

    </form>

</div></div>                                </div>
<div class="col-lg-4" >
    <div class="card">
        <div class="card-header">
                        <strong>Questions   </strong>
            <button class="btn btn-success" onclick="afficher()" >correction</button>
                      </div>

                                        <div class="card-body">

{% for question in liste %}

{%for id1 in l %}
{%if id1 == question.id and id1 == quest.id%}
<a href="{{question.id}}" class="btn  btn-primary" style="margin:3px">{{forloop.parentloop.counter}}</a>
                                                   {%endif%}
                                            {%if id1 == question.id and id1 != quest.id%}

<a href="{{question.id}}" class="btn  btn-danger" style="margin:3px">{{forloop.parentloop.counter}}</a>
                                            {%endif%}
  {%endfor%}
                                            {%for id2 in listevider %}
                                            {%if id2 == question.id and id2 == quest.id %}

                                             <a href="{{question.id}}" class="btn btn-primary " style="margin:3px">{{forloop.parentloop.counter}}</a>

                                                                                        {%endif%}
                                            {%if id2 == question.id and id2 != quest.id%}

                                             <a href="{{question.id}}" class="btn  btn-success" style="margin:3px">{{forloop.parentloop.counter}}</a>

                                                                                        {%endif%}

  {%endfor%}

                                            {%endfor%}

</div>
    </div>
</div>
<center><a href="/exam/{{examen_id}}/resultExam" class="btn btn-block btn-primary">Finish</a> </center>
<p id="demo"></p>
    <div class="card-body" style="visibility:hidden" id="affiche">





     {%if quest.multi_choice_answer_set.all %}
                                                 <div class="col col-md-3"><label class=" form-control-label">{{quest.header_text}}</label></div>
                            <div class="col col-md-3">
                              <div class="form-check">
                                   {%for choix in quest.multi_choice_answer_set.all %}
                                <div class="radio">
                                  <label class="form-check-label ">
                                    {%if choix.points == 0%}
                                      <input type="checkbox"  name="radiosM" class="form-check-input" readonly="readonly" disabled >{{choix.multi_variant}}
                                  {%else%}
                       <input type="checkbox"  name="radiosM" class="form-check-input" checked readonly="readonly"disabled >{{choix.multi_variant}}

                                                                         {%endif%}

                                  </label>
                                </div>

                                  {%endfor%}

                              </div>
                            </div>
        <div class="col col-md-3">{{quest.description}}</div>
         <div class="col col-md-3"><label>explanation:</label> <br> {{quest.footer_text}}</div>
               {%endif%}
{%if quest.one_answer_set.all %}
                                                 <div class="col col-md-3"><label class=" form-control-label">{{quest.description}}</label></div>
                            <div class="col col-md-3">
                              <div class="form-check">
                                   {%for choix in quest.one_answer_set.all %}
                                <div class="radio">
                                  <label class="form-check-label ">
                                    {%if choix.points == 0%}

                            <input type="radio"  name="radios"  class="form-check-input" disabled>{{choix.answer_variant}}
                                  {%else%}
                                      <input type="radio"  name="radios"  class="form-check-input" checked disabled>{{choix.answer_variant}}

                                   {%endif%}
                                  </label>
                                </div>

                                  {%endfor%}

                              </div>
                            </div>
 <div class="col col-md-3">{{quest.description}}</div>
         <div class="col col-md-3"><label>explanation:</label> <br> {{quest.footer_text}}</div>
               {%endif%}
                                {%if quest.free_text_set.all %}



          {%for choix in quest.free_text_set.all %}
 <div class="row form-group">
                            <div class="col col-md-3"><label class=" form-control-label">{{quest.description}}</label></div>
<div class="col-12 col-md-9">


    <textarea name="text"  rows="9"  placeholder="Content..." class="form-control" readonly="readonly" >{{choix.text}}</textarea>



    </div> <div class="col col-md-3">{{quest.description}}</div>
         <div class="col col-md-3"><label>explanation:</label> <br> {{quest.footer_text}}</div>
                          </div>

    <br>{%endfor%}


                                               {%endif%}



</div></div>

<!--retour du debut c est pour cela en doit stoker la variable dans une valeur poste pour qu il soit un raffrechissement-->
<!--remplacer l expression de expirer par un arret brusque de systeme en ajoutant une variable de retour vers django et faire comme condition d arret -->
<!--timer c est le temps de l examen qui doit etre changer en django ulterieurment-->
<script>
// Set the date we're counting down to
if ("{{first}}"==1){

var Timer=60*{{timer}} * 1000;
var countDownDate = new Date();
countDownDate.setTime(countDownDate.getTime() + Timer);
val=countDownDate+"";
document.getElementById('time').value=countDownDate;}
else{
var countDownDate=new Date(document.getElementById('time').value);
}

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
  if ({{timer}}!=10000){
    // Find the distance between now and the count down date
    var distance =countDownDate- now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    // Output the result in an element with id="demo"

    document.getElementById("demo").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";}

    // If the count down is over, write some text
    if (distance < 0) {
        clearInterval(x);
        window.stop();
        document.getElementById("demo").innerHTML = "EXPIRED";

        window.location.href="/exam/{{examen_id}}/result";
    }
}, 1000);

function afficher() {
document.getElementById('affiche').style.visibility = 'visible';
}
</script>

{% endblock %}

exam/templates/exam/certificat.html
{% extends my_template %}


{% block title %}Quiz{% endblock %}

{% block content %}

{% for certificat in certif %}
{%if certificat.exam.certified = True %}

  <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="/exam{{certificat.exam.logo.url}}" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>{{certificat.exam.name}}</h3>
            <a class="btn btn-primary" href="{% url 'imprimeCertif' certificat.exam.id %}">imprime</a>




        </div>
      </div>
{%endif%}

{%endfor%}






{% endblock %}

exam/templates/exam/passeExam.html
{% extends my_template %}

{% block title %}Quiz{% endblock %}

{% block content %}

                            <div class="card" >
                                <div class="card-header">
                                    <h4>Exam {{examen.name}}</h4>
                                </div>
                                <div class="card-body">

<div class="col-lg-8" >
    <center><h1>Commancer</h1></center>
</div>
<div class="col-lg-4" >
                                                 {% for question in examen.question_set.all %}
    {%if forloop.counter == 1 %}
<a href="{{firstid}}" class="btn btn-block btn-success">commancer</a>
{%endif%}
                                            {%endfor%}

</div>

                                </div>
                            </div>





{% endblock %}